V0.9.0 index
kenlabs/go-ipfs pull request #2
Opened 2021-08-12 14:58 UTC by jackz-jones

new feature:
- support the index option when adding
- auto send cid list to indexer node when adding

2021-08-13 11:26 UTC, sugarforever requested changes

2021-08-13 11:34 UTC, bsjohnson01 commented on core/coreunix/add.go
> +		indexHost := os.Getenv("INDEX_NODE_URL")
建议这项配置也使用命令行和配置文件，用环境变量有点坑……

2021-08-14 06:00 UTC, jackz-jones commented on core/coreunix/add.go
> +func creatCidFile(cidList []string) error {
Done

2021-08-14 06:00 UTC, jackz-jones commented on index.md
> +```
Done

2021-08-14 06:01 UTC, jackz-jones commented on core/coreunix/add.go
> +		if indexHost == "" {
Done

2021-08-14 14:05 UTC, jackz-jones commented on core/coreunix/add.go
> +		indexHost := os.Getenv("INDEX_NODE_URL")
@bsjohnson01 Done

有如下调整：
- config文件配置项名称修改改为 IndexEnable
- add文件使用 --index-node http://... 形式
- 不用再设置环境变量 INDEX_NODE_URL

2021-08-16 12:48 UTC, sugarforever approved these changes

2021-08-16 21:59 UTC, merged